version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: hola-flask-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: msfuser
      POSTGRES_PASSWORD: msfpass2026!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U msfuser -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: hola-flask-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: adminmsf@byronrm.com
      PGADMIN_DEFAULT_PASSWORD: adminmsf12345
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    ports:
      - "5050:80"
    networks:
      - backend
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.pgadmin.rule=Host(`pgmsf.byronrm.com`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
  traefik-public:
    external: true
