version: '3.9'
services:
  michael:
    image: ghcr.io/michaeldlt1/holaflask:latest
    container_name: hola-flask-app
    networks:
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5000/ >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.michael.rule=Host(`caiza.byronrm.com`)"
      - "traefik.http.routers.michael.entrypoints=websecure"
      - "traefik.http.routers.michael.tls=true"
      - "traefik.http.routers.michael.tls.certresolver=letsencrypt"
      - "traefik.http.services.michael.loadbalancer.server.port=5000"

networks:
  traefik-public:
    external: true