version: '3.9'
services:
  michael:
    image: ghcr.io/michaeldlt1/holaflask:latest
    networks:
      - proxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.michael.rule=Host(`caiza.byronrm.com`)"
      - "traefik.http.routers.michael.entrypoints=websecure"
      - "traefik.http.routers.michael.tls=true"
      - "traefik.http.routers.michael.tls.certresolver=letsencrypt"
      - "traefik.http.services.michael.loadbalancer.server.port=5000"

networks:
  proxy:
    external: true